services:
  shop.webapi:
    image: shop.webapi
    ports:
      - "9000:8080"
    networks:
      - shop-net
    depends_on:
      - mysql
      - redis
      - rabbitmq
    build:
      context: .
      dockerfile: src/Shop.WebApi/Dockerfile
  redis:
    image: redis:latest
    container_name: demo-shop-redis
    ports:
      - "6378:6379"
    volumes:
      - /home/demo-shop/redis/data:/data
    restart: always
    networks:
      - shop-net
    deploy:
      resources:
        limits:
          memory: 50M
    command: redis-server --appendonly yes --requirepass qGmNTfPtbQYMX6Qz

  mysql:
    image: mysql:latest
    container_name: demo-shop-mysql
    ports:
      - "3305:3306"
    volumes:
      - /home/demo-shop/mysql:/var/lib/mysql
    restart: always
    networks:
      - shop-net
    deploy:
      resources:
        limits:
          memory: 1G
    environment:
      - MYSQL_ROOT_PASSWORD=nzuxZ3Wf4aqfWfGz
      - TZ=Asia/Shanghai
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  rabbitmq:
    image: rabbitmq:3-management
    container_name: demo-shop-mq
    ports:
      - "5671:5672"
      - "15671:15672"
    volumes:
      - /home/demo-shop/rabbitmq:/var/lib/rabbitmq
    restart: always
    networks:
      - shop-net
    deploy:
      resources:
        limits:
          memory: 500M
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=7BKq9vFAqz6Puzjj

networks:
  shop-net:
    external: true